version: '3.9'
services:
  weatherapp_backend:
    build:
      context: ./backend
    image: weatherapp_backend
    ports:
        - 9000:9000
    # volumes:
    #   - ./backend/src:/backend/src
    environment:
      APPID: 278cbac3c8cf37ee98649913a4ec6bf2

  weatherapp_frontend:
    build:
      context: ./frontend
    image:  weatherapp_frontend
    ports:
      - 8000:8000
    # volumes:
    #   - ./frontend/src:/frontend/src
    environment:
      - ENDPOINT=${ENDPOINT:-`curl http://169.254.169.254/latest/meta-data/local-ipv4`}